### ISSUE TITLE
All badges have the same behaviour

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/DataHUB#38]
Not sure if this behaviour is intended or if this repo is the correct place. 

![image](https://github.com/user-attachments/assets/1fb4cbe1-efc6-4d40-b79f-fb7540e76bc0)

I have an ARC where I added the invenio and the plant-growth packages. When they're both passing and I click on any of the badges, I'm redirected to the ARCigator page. If the plant-growth package is not passing, clicking on the badges leads you to the tests page.

IMO clicking on the plant-growth badge should redirect to the tests page anyways (to e.g. see the non-critical failing tests) and only clicking on the invenio badge should redirect to the ARCigator page.

**Comment by j-bauer** [comment]
@HLWeil can you confirm that this now works as expected? Then we can close this issue.
