### ISSUE TITLE
Seeing all projects when being logged in

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/DataHUB#8]
When being logged in in the DataPLANT DataHUB and navigating to "View all projects", only own projects or projects in which I am participating are shown. Public ARCs can only be seen when being logged out.

It would be good to being able to navigate into public ARCs also when being logged in.
Maybe there is a hidden setting me and other users can change to select for this behaviour?

**Comment by j-bauer** [comment]
We just had a look at this and when you are right: we logged in, you only see your projects and those you have explicit access to in the "Projects" area. However, from there you can click on the top-right side of the page on "Explore projects" and you are redirection to `/explore` where you can see the public projects.

**Comment by andreaschrader** [comment]
PR in Knowledge Base: https://github.com/nfdi4plants/nfdi4plants.knowledgebase/pull/342
Closed here.
