### ISSUE TITLE
Template still create a master branch

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/DataHUB#9]
Alredy an issue before (#2).

When creating an ARC from the template, a master branch is created.
This causes problems with syncing as an additional main branch is created and likely also preventing to open this ARC with the ARCitect after it has been cloned before and not synced before.

Wanted: Change the template to create a branch named "main".

**Comment by CMR248** [comment]
@j-bauer

**Comment by j-bauer** [comment]
While testing the upgrade to the latest GitLab version (16.7.3) I tested the ARC import feature and the branch was named `main` during my testing. Can you please test with the new version and see if that is still an issue?

**Comment by andreaschrader** [comment]
Created a fresh template.
The main branch ist still named 'master'.
<img width="1128" alt="Screenshot 2024-01-18 at 15 36 11" src="https://github.com/nfdi4plants/DataHUB/assets/85687301/9d78294f-ba57-40a5-a4e7-8d17e5859e87">

**Comment by j-bauer** [comment]
is that with the new datahub image that we created yesterday?

**Comment by andreaschrader** [comment]
I logged in the "DataHUB (reference)" HUB.

**Comment by j-bauer** [comment]
> I logged in the "DataHUB (reference)" HUB.

Ah ok, yes the template is not yet up-to-date on the productive DataHUB, I thought you were talking about an on-premise instance.

We will update the main DataHUB soon and then the template will create a `main` branch instead of `master`.

**Comment by andreaschrader** [comment]
Great! Will test it next week again :)

**Comment by j-bauer** [comment]
Not sure excatly when we'll perform the update, but I'll let you know.
